version: '3.1'

networks:
  ds_net:
    external: true

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    volumes:
      - ./zoo/conf/zoo.cfg:/conf/zoo.cfg
      - ./zoo/1:/var/lib/zookeeper
    networks:
      ds_net:
        ipv4_address: 172.18.0.2

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    volumes:
      - ./zoo/conf/zoo.cfg:/conf/zoo.cfg
      - ./zoo/2:/var/lib/zookeeper
    networks:
      ds_net:
        ipv4_address: 172.18.0.3
        
  zoo3:
    image: zookeeper
    restart: always
    hostname: zoo3
    volumes:
      - ./zoo/conf/zoo.cfg:/conf/zoo.cfg
      - ./zoo/3:/var/lib/zookeeper
    networks:
      ds_net:
        ipv4_address: 172.18.0.4
        
  california1:
    build: .
    image: electionserver
    restart: always
    hostname: california1
    networks:
      ds_net:
        ipv4_address: 172.18.0.5
    environment:
      IP: 172.18.0.5
      STATE: california
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  california2:
    image: electionserver
    restart: always
    hostname: california2
    networks:
      ds_net:
        ipv4_address: 172.18.0.8
    environment:
      IP: 172.18.0.8
      STATE: california
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  california3:
    image: electionserver
    restart: always
    hostname: california3
    networks:
      ds_net:
        ipv4_address: 172.18.0.11
    environment:
      IP: 172.18.0.11
      STATE: california
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  texas1:
    image: electionserver
    restart: always
    hostname: texas1
    networks:
      ds_net:
        ipv4_address: 172.18.0.6
    environment:
      IP: 172.18.0.6
      STATE: texas
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  texas2:
    image: electionserver
    restart: always
    hostname: texas2
    networks:
      ds_net:
        ipv4_address: 172.18.0.9
    environment:
      IP: 172.18.0.9
      STATE: texas
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  texas3:
    image: electionserver
    restart: always
    hostname: texas3
    networks:
      ds_net:
        ipv4_address: 172.18.0.12
    environment:
      IP: 172.18.0.12
      STATE: texas
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  new_york1:
    image: electionserver
    restart: always
    hostname: new_york1
    networks:
      ds_net:
        ipv4_address: 172.18.0.7
    environment:
      IP: 172.18.0.7
      STATE: new_york
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  new_york2:
    image: electionserver
    restart: always
    hostname: new_york2
    networks:
      ds_net:
        ipv4_address: 172.18.0.10
    environment:
      IP: 172.18.0.10
      STATE: new_york
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181

  new_york3:
    image: electionserver
    restart: always
    hostname: new_york3
    networks:
      ds_net:
        ipv4_address: 172.18.0.13
    environment:
      IP: 172.18.0.13
      STATE: new_york
      ZKHOST: zoo1:2181,zoo2:2181,zoo3:2181