version: '3.1'

networks:
  ds_net:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "false"
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16

services:
  zoo1:
    image: zookeeper
    restart: always
    hostname: zoo1
    networks:
      ds_net:
        ipv4_address: 172.18.0.2
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181 server.2=zoo2:2888:3888;2181

  zoo2:
    image: zookeeper
    restart: always
    hostname: zoo2
    networks:
      ds_net:
        ipv4_address: 172.18.0.3
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888;2181 server.2=0.0.0.0:2888:3888;2181

  california1:
    build: .
    image: electionserver
    restart: always
    hostname: california1
    networks:
      ds_net:
        ipv4_address: 172.18.0.5
    environment:
      IP: 172.18.0.5
      STATE: california
      ZKHOST: zoo1:2181,zoo2:2181

  california2:
    image: electionserver
    restart: always
    hostname: california1
    networks:
      ds_net:
        ipv4_address: 172.18.0.8
    environment:
      IP: 172.18.0.8
      STATE: california
      ZKHOST: zoo1:2181,zoo2:2181

  texas1:
    image: electionserver
    restart: always
    hostname: texas1
    networks:
      ds_net:
        ipv4_address: 172.18.0.6
    environment:
      IP: 172.18.0.6
      STATE: texas
      ZKHOST: zoo1:2181,zoo2:2181

  new_york1:
    image: electionserver
    restart: always
    hostname: new_york
    networks:
      ds_net:
        ipv4_address: 172.18.0.7
    environment:
      IP: 172.18.0.7
      STATE: new_york
      ZKHOST: zoo1:2181,zoo2:2181